### ISSUE TITLE
Filtering selected colums

### ISSUE THREAD

**Issue by mikies21** [dreamRs/datamods#23]
Hi, I really love this package and what you are doing!
I have an issue with the filter_data_server(). I am trying to filter selected columns however I keep running into errors.

here's the example:
UI
```
shinyUI(
  navbarPage("ShinybeetleNMR",
    theme = shinytheme("yeti"),
    tabPanel(
      "input NMR files",
      fluidPage(fluidRow(
        column(
          3,
          import_file_ui("new_upload"),
          update_variables_ui("var_update")
        ),
        column(
          3,
          sliderInput("metadata_index", label = "group annotations columns", min = 1, max = 10, step = 1, value = c(1, 8)),
          filter_data_ui("filtering_data", max_height = "500px")
        )))))))
````
SERVER
````
shinyServer(function(input, output) {
#upload new data
new_data <- import_file_server(id = 'new_upload',btn_show_data = T,trigger_return = 'change', return_class = 'data.frame')

#update variables
new_variable <- update_variables_server('var_update',data = new_data$data)

#get the columns  to filter from a slider input
metadata <- reactive({
    names_to_filter <- colnames(new_variable()[,input$metadata_index[1]:input$metadata_index[2]])
    names_to_filter
  })

#filter the dataframe
filtered_data <- filter_data_server(id = 'filtering_data', data = new_variable, vars = metadata)
})
````

the error I get is:
Text to be written must be a length-one character vector

would you have any idea of why this is happening, I have tried different approaches but they all throw errors at me

**Comment by pvictor** [comment]
Hello, thank you !

Which version do you use ? Can you try with latest CRAN version or with GitHub version ?
With last version, I ran your code without error.

Victor

**Comment by drhudgins** [comment]
I had the same issue until used as.list(). Like below.
metadata <- reactive({
    names_to_filter <- colnames(new_variable()[,input$metadata_index[1]:input$metadata_index[2]])
    as.list(names_to_filter)
  })
