### ISSUE TITLE
Issues importing `.sas7bdat` files

### ISSUE THREAD

**Issue by jwildfire** [dreamRs/datamods#24]
I'm having issues loading `.sas7bat` files using the `import_file` module. Pretty sure the issue is with the `dec` option. SAS files loaded as expected when I commented out [this line](https://github.com/dreamRs/datamods/blob/35748730e38ac37e533e78510af6a09141bbcd79/R/import-file.R#L190), so I added an additional layer of `ifelse()` in `jwildfire/datamods` , which seems to clear up the issue. I'll file a PR shortly. 

Thanks for the great package! We're using both the file load and filtering functionality extensively in the upcoming release of the [safetyGraphics package](https://github.com/SafetyGraphics/safetyGraphics/). Prototype using {datamods} filtering [here](https://git866.shinyapps.io/safetyGraphics_v2_demo/).

**Comment by pvictor** [comment]
Thanks for the PR!
Nice and complex app 👍
