### ISSUE TITLE
Re-import the same data twice in a row

### ISSUE THREAD

**Issue by RB000** [dreamRs/datamods#27]
Hello, 

I imported a dataset and then I wanted to update the type of variables so i reimport the same data but the button "import data" remains disable. 

![image](https://user-images.githubusercontent.com/28759682/131813887-f30d6ee6-cc1b-455d-8121-06d2c3557305.png)

**Comment by pvictor** [comment]
Hello,

Which version do you use ? If not 1.1.5, can you try to update  ?

Victor

**Comment by RB000** [comment]
Thank you 
It works correctly after the update :)
