### ISSUE TITLE
incorrect reading of txt files (removes rows with an empty value automatically)

### ISSUE THREAD

**Issue by dannyvolkaerts** [dreamRs/datamods#30]
When using datamods feature in esquisse (importing data) esquisse automatically removes rows with empty values instead of assigning NA values to them. I have experienced this with txt files. It shows the correct code after importing (and so admitting it has deleted the rows with empty values for a certain column).
Try yourself importing the attached file -> code after importing file: Pokemon_dataset.txt %>% filter(!(Type2 %in% ""))
[Pokemon_dataset.txt](https://github.com/dreamRs/esquisse/files/7178320/Pokemon_dataset.txt)

R version: 4.0.0
Esquisse version: 1.0.2.9000

FYI: this is not the case when reading the txt file in R with readr package and saving it as Rdata file. Then missing values are handled as expected (indication of 52% missing values for 'type2' without auto filtering it)

**Comment by pvictor** [comment]
Thanks for reporting this, I see 2 problems:

* empty strings are not read as `NA` (maybe it should an input parameter)
* empty strings are ignored in filter module

**Comment by mbauwens** [comment]
has this issue already been followed up/resolved? I've experienced the same problems as @dannyvolkaerts

**Comment by pvictor** [comment]
Can you share the data with which there is a problem @mbauwens ?

**Comment by mbauwens** [comment]
I've upgraded to R 4.0.5 and Esquisse 1.0.0 since and the issue has been resolved, probably from release v0.2.3 :)

**Comment by pvictor** [comment]
Thanks for checking @mbauwens :+1:
