### ISSUE TITLE
Give option for accepted file extensions in `import_file` module [Feature Request]

### ISSUE THREAD

**Issue by kyleweise** [dreamRs/datamods#35]
Hello! 

It would be nice to have the functionality to provide the `import_file` module with a list of acceptable file extensions (.csv, .xlsx, etc), instead, by default, accepting everything. Let me know your thoughts. 

Best,

-Kyle

**Comment by pvictor** [comment]
Yes good idea.

`import_file_ui()` has now a `file_extensions` argument to specify diles that can be imported.
And `import_file_server()` has an argument `read_fns` to custom functions to read data according to file's extension.

Victor

**Comment by kyleweise** [comment]
Hi Victor,

Thanks for getting to this so quickly! I just had one issue. Since this functionality is brand new, it's obviously not on the version thats available on CRAN. So, I deleted my local installation and installed again with `remotes::install_github("dreamRs/datamods")`, and not sure what happened with am getting error when trying to tab-complete:

```
Error in fetch(key) : 
  lazy-load database '/home/kweise/R/x86_64-pc-linux-gnu-library/4.0/datamods/help/datamods.rdb' is corrupt
```

Don't believe it's on my end, so I'm thinking it's an issue in how the package is built.

Thanks!

-Kyle

**Comment by kyleweise** [comment]
Nevermind! Restarted my R session and all is good 😄  Feel free to close this issue when you feel necessary. Thanks again, Victor.

Best,
-Kyle

**Comment by kyleweise** [comment]
Actually one other thing 😅 . I think you'll want to change:

https://github.com/dreamRs/datamods/blob/f0725976e28313aa62f5e272868d80c3b388827b/R/import-file.R#L98

to use the new `file_extensions` parameter. So maybe something like:


`i18n(glue("Please only upload {file_exts} files", file_exts = paste(file_extensions, collapse = " "))), `

I'm sure you could think of something more elegant.

**Comment by pvictor** [comment]
Indeed you're right, I changed it, thanks.

Victor
