### ISSUE TITLE
filter_data_server and single-column data

### ISSUE THREAD

**Issue by ProfessorPeregrine** [dreamRs/datamods#36]
Love this function, but I think I am running into a bug unless I have made some error in configuration.

If I import a single-column data source (as a data frame) before I adjust the sliders it displays the data. Once I move the dynamic filter sliders, I get an error from datatables that 'data must be 2-dimensional (e.g. data frame or matrix)'

It works perfectly for multiple column data.

It looks like the function is not returning a data frame for single columns - could that be possible? I have tried both integer and non-integer data.

**Comment by pvictor** [comment]
It should be fixed if you re-install from GitHub.
This was caused by the behavior of `data.frame` to simplify the dimensions of an object if possible:

```r
mtcars[, "mpg"]
# versus
mtcars[, "mpg", drop = FALSE]
```

Victor

**Comment by ProfessorPeregrine** [comment]
Awesome - checking now!
