### ISSUE TITLE
Filtering doesn't work with additional datatable with filter option in combination with eventReactive

### ISSUE THREAD

**Issue by cjprobst** [dreamRs/datamods#38]
I tried to develop the filtering example with another table showing in the app. Everything works fine until I set the filter option in the second table to "top" instead of "none" and using an eventReactive instead of an reactive (which is fine without the additional table)

Example:
`library(shiny)
library(shinyWidgets)
library(datamods)
library(tidyverse)
library(DT)

ui <- fluidPage(

  actionButton('bt_load', label = 'Load Data', icon = icon("upload")),
  
  fluidRow(
    column(
      width = 3,
      filter_data_ui("filtering", max_height = "500px")
    ),
    column(
      width = 9,
      DT::dataTableOutput(outputId = "dt_filter")
      , DT::dataTableOutput(outputId = "dt_extra")
    )
  )
)

server <- function(input, output, session) {
  
  data_test <- eventReactive(input$bt_load, {
  #data_test <- reactive({
    diamonds
  })
  
  
  res_filter <- filter_data_server(
    id = "filtering",
    data = data_test,
    name = reactive("data_test"),
    vars = reactive(NULL),
    widget_num = "slider",
    widget_date = "slider",
    label_na = "Missing"
  )
  
  output$dt_filter <- DT::renderDT({
    res_filter$filtered()
  }, options = list(pageLength = 5))
  
  
  output$dt_extra = DT::renderDataTable(datatable(iris, filter = 'top'))
  
}

shinyApp(ui, server)`

![image](https://user-images.githubusercontent.com/95871833/145432628-548ad10f-40d0-4870-bc0e-b87f7d5d2272.png)

instead of

![image](https://user-images.githubusercontent.com/95871833/145432725-de3f58a5-16fa-465f-9aa3-d5f9a4163e8c.png)

Tested with 

R version 4.1.2 on Windows
DT_0.19, shiny_1.7.1, datamods_1.2.0

and

R version 3.5.1 Debian GNU/Linux 9
DT_0.18, shiny_1.5.0, datamods_1.2.0

Thanks for any help
Christine

**Comment by pvictor** [comment]
Hello Christine,

Seems related to this issue in Shiny : https://github.com/rstudio/shiny/issues/3125
If you add this line somewhere in your UI, this should work fine:

```r
htmltools::findDependencies(selectizeInput("foo", "bar", choices = "a"))
```

Victor

**Comment by cjprobst** [comment]
Hello Victor,

thank you for finding the related issue. The workaround works fine for me at this moment.
I will close this issue here and keep track of the other one.

Christine
