### ISSUE TITLE
Import from URL

### ISSUE THREAD

**Issue by struckma** [dreamRs/datamods#42]
Thank you for this great package, I thought, there should be an existing solution for such a common problem like reading in a data frame in an R GUI, and was surprised by the great options of `datamods`. Thank you for that. However, I have a feature request here.

Many data sets are available as e.g. CSV files from URLs in the internet. With the file widget, I can only select local files, with the Google-Widget only Google spreadsheets. Since `rio::import` also supports URLs in its `file` argument (according to its manual, version 0.5.27), it should be a low-hanging fruit to have a widget for reading files from URLs.

Therefore, I would like to put a feature request here for a new import-class for external files.

**Comment by pvictor** [comment]
Hello,
If you re-install from GitHub with:

```r
remotes::install_github("dreamRs/datamods")
```

there's a new module called `import_url_ui()` / `import_url_server()` added in https://github.com/dreamRs/datamods/pull/39 that may serve your needs.

It's not yet on CRAN, but i'll try to submit soon.

Victor

**Comment by struckma** [comment]
Yes, indeed, that works great, sorry for the duplicate.
