### ISSUE TITLE
UI Filters to be placed in different locations

### ISSUE THREAD

**Issue by hairen-k** [dreamRs/datamods#53]
Hello, really love the package, Thanks!

I was wondering if there's a way to place input filters in different parts of the App but referring to the same server.
Let me explain it better: I have many filters and I don't want to place all of them in a sidebar column. I need half of them there and the others at the top of the Main Panel, for example. Is that feasible as of now?  

Alternatively, I was wondering if there's a way to have 2 pairs of UI/Server with different ids and still produce a coherent res_filter$filtered in the end?
As of now, the only thing I came up with is giving as data input of filters server number 1 the output of the filters server number 2 but this only works under one annoying condition: all the filters in the server number 2 have to be applied strictly before applying filters server number 1.

Some workaround idea?

Thanks,
Gaspare

**Comment by pvictor** [comment]
Hello,
No that's not currently possible but you can still use the module twice with different variables and then combine the results in the server.

Victor
