### ISSUE TITLE
Possibility to add other read_funs parameters in import_file?

### ISSUE THREAD

**Issue by chabrault** [dreamRs/datamods#57]
Thanks a lot for your useful package!
I was wondering if it could be possible to pass other parameters to `read_funs()` in `import_file_server()` function?
In particular, I would like to specify the date format as '%d/%m/%Y' by default and specify custom na strings. I use the function to import Excel files (.xlsx or .xls).

**Comment by pvictor** [comment]
You can use any parameters you want in the function : 

```r
import_file_server(
  id = "myid",
  read_fns = list(
    xlsx = function(file, sheet, skip) {
      readxl::read_excel(path = file, sheet = sheet, skip = skip, na = c("-", "-999"))
    },
    xls = function(file, sheet, skip) {
      readxl::read_excel(path = file, sheet = sheet, skip = skip, na = c("-", "-999"))
    }
  )
)
```

The module will try to pass those arguments, defined in the interface, to the function, but you can ignore them if you don't use them : 

* file = path to file
* sheet = sheet number
* skip = number of rows to skip
* dec = decimal separator
* encoding = encoding

**Comment by chabrault** [comment]
Thank you for your answer. One other thing, would it be possible to define `read_funs` directly in `import_server` function?

**Comment by pvictor** [comment]
I'm not sure I understand what you mean..

**Comment by chabrault** [comment]
Sorry I'll try to explain better.
I'm loading data from file or copy-paste using `import_modal` and `import_server` functions. If I understood correctly, `read_funs` is a parameter of `import_file` function, which itself is called in `import_server`. Would it be possible then to add a parameter `read_funs` to `import_server`, which will be passed to `import_file`?

The objective would be to load the files using this command;
```{r}  
imported <- datamods::import_server("import_modal",
                                        allowed_status="OK",
                                        return_class = "data.frame",
                                        read_fns = list(
                                          xlsx = function(file, sheet, skip) {
                                            readxl::read_excel(path = file, sheet = sheet, skip = skip, na = c("-", "-999"))
                                          },
                                          xls = function(file, sheet, skip) {
                                            readxl::read_excel(path = file, sheet = sheet, skip = skip, na = c("-", "-999"))
                                          }
                                        )
    )
```

**Comment by pvictor** [comment]
Thanks, yes that's not possible right now, I will add this in the next release.
