### ISSUE TITLE
Unexpected Filters applied when initializing filter module

### ISSUE THREAD

**Issue by jwildfire** [dreamRs/datamods#60]
I'm seeing some [unexpected filters in the `safetyGraphics` shiny app](https://github.com/SafetyGraphics/safetyGraphics/issues/697) when using the `datamods` filter module. This is (relatively) new behavior was almost certainly introduced in a 2022 `datamods` update. 

I'll dig in more and try to debug in the next few days, but just wanted to check with you all to see if this was a known issue or if there's a new setting I need to tweak. 

Thanks for any help (and for the great package)!

**Comment by jwildfire** [comment]
Changing the `widget_char` param in `filter_data_server` from "virtualSelect"  to just "select" resolves my issue, so not going to dig further in to the root cause at this time. I'll close this issue, but happy to test with the nicer "virtualSelect" if you all have ideas about what's going on there.

**Comment by pvictor** [comment]
Thanks for reporting it, i will investigate.

Victor
