### ISSUE TITLE
Issue adding row with edit_data_server

### ISSUE THREAD

**Issue by PhillipJones405** [dreamRs/datamods#74]
I am trying to use the edit_data_server function to create a dataframe that I can then add rows to. The example works fine, but when i use my own dataframe I recieve this error:
Error in rbindlist(l, use.names, fill, idcol) : 
  Class attribute on column 3 of item 2 does not match with column 3 of item 1.

The dataframe I made is just a single row and column. I have tried it with other dataframes as well. 
Here is the code:

```
library(shiny)
library(datamods)
library(bslib)

ui <- fluidPage(
  theme = bs_theme(
    version = 5
  ),
  tags$h2(i18n("Edit data"), align = "center"),
  edit_data_ui(id = "id"),
  verbatimTextOutput("result")
)

dataframe_test <- data.frame('groupName' = 0)

server <- function(input, output, session) {

  edited_r <- edit_data_server(
    id = "id",
    #data_r = reactive(demo_edit),
    data_r = reactive(dataframe_test),
    add = TRUE,
    update = TRUE,
    delete = TRUE,
    download_csv = TRUE,
    download_excel = TRUE,
    file_name_export = "datas",

  )
  
  output$result <- renderPrint({
    str(edited_r())
  })
  
}

if (interactive())
  shinyApp(ui, server)

```

**Comment by pvictor** [comment]
Thanks for reporting this issue. This should be fixed if you re-install from GitHub.

Victor

**Comment by PhillipJones405** [comment]
That worked! Thank you.
