### ISSUE TITLE
Page scrolling down automatically upon shiny app loading

### ISSUE THREAD

**Issue by lucalamoni** [dreamRs/datamods#94]
Hi, 
I have developed this shiny app for my organization https://ices-taf.shinyapps.io/advicexplorer/
On the first page, I have a filtering panel on the left, that includes 2 virtualSelectInput followed by 1 select_group_ui module. 
After I implemented these new functions (I used to use selectizeInput) I started to notice that whenever the app loads for the first time or whenever I select a region from the map, the page scrolling jumps down by itself and the last field of the select_group_ui module gets highlighted.
Do you think that this might have something to do with the select_group_ui module? (I don't get any error message and I changed selectizeGroupServer because I read that is not going to be maintained)
Thank you for your help!
Best regards
Luca

**Comment by pvictor** [comment]
Nice app!
Yes sorry for that, that's a bug in [`virtual-select` library](https://github.com/sa-si-dev/virtual-select) used by [`shinyWidgets::virtualSelect()`](https://dreamrs.github.io/shinyWidgets/reference/virtualSelectInput.html) (and `selectgroup` module)
If you re-install {shinyWidgets} from GitHub it should be fixed : 

```r
remotes::install_github("dreamRs/shinyWidgets")
```

Victor

**Comment by lucalamoni** [comment]
Thank you so much Victor!!
