### ISSUE TITLE
Select All Checkbox not rendering in select_group_ui

### ISSUE THREAD

**Issue by yaswant-krishna** [dreamRs/datamods#99]
### Issue Description

Hello,

When `select_group_ui` is used with `multiple = TRUE`, the checkbox to select all is not being displayed.

```r
library(shiny)
library(shinydashboard)
library(datamods)
library(shinyWidgets)

ui <- shinydashboard::dashboardPage(
  shinydashboard::dashboardHeader(),
  shinydashboard::dashboardSidebar(
    shinyWidgets::dropMenu(
      shiny::actionButton(
        inputId = "iqvia", 
        label = "IQVIA", 
        style = "color: #000000; background-color: #d1e8f0; border-color: #2e6da4; width:200px;"
      ),
      select_group_ui(
        id = "my-filters",
        inline = FALSE,
        params = list(
          list(inputId = "Manufacturer", label = "Manufacturer:"),
          list(inputId = "Type", label = "Type:"),
          list(inputId = "AirBags", label = "AirBags:"),
          list(inputId = "DriveTrain", label = "DriveTrain:")
        ), 
        vs_args = list(
          multiple = TRUE, 
          search = TRUE, 
          selected = TRUE, 
          noOfDisplayValues = 1, 
          dropboxWidth = "200%", 
          position = "bottom"
        )
      )
    )
  ),
  shinydashboard::dashboardBody()
)

server <- function(input, output) {
  res_mod <- select_group_server(
    id = "my-filters",
    data = reactive(MASS::Cars93),
    vars = reactive(c("Manufacturer", "Type", "AirBags", "DriveTrain"))
  )
}

shiny::shinyApp(ui, server)
```

### Output
![image](https://github.com/dreamRs/datamods/assets/144750215/4276d6ac-30fb-46b9-9772-40f57208f65e)

### Expected Output
![image](https://github.com/dreamRs/datamods/assets/144750215/16530d0e-61d4-4f22-adb3-cdd2338ae4a6)

Regards,
Yaswant Krishna.

**Comment by pvictor** [comment]
Hello,
You have to use `disableSelectAll = FALSE` in `vs_args` list of options.

Victor

**Comment by yaswant-krishna** [comment]
I have used `disableSelectAll = FALSE` in vs_args list of options but still I am not able to see the checkbox.

### Output after using  `disableSelectAll = FALSE`
![image](https://github.com/dreamRs/datamods/assets/144750215/a7bf659a-3206-4c0e-b581-2fcad24e26b2)

Regards,
Yaswant.

**Comment by pvictor** [comment]
Try the dev version by reinstalling from GitHub.

Victor

**Comment by yaswant-krishna** [comment]
Tried the dev version, it worked. Thanks!

Yaswant Krishna.
